# Generated by Django 3.2.5 on 2021-07-27 15:41

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('photo', cloudinary.models.CloudinaryField(default='Image', max_length=255, verbose_name='image')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pollution_type', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=40)),
                ('estimate', models.CharField(max_length=3)),
            ],
        ),
    ]
