# Generated by Django 3.2.5 on 2021-07-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cleanup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('organizer', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('paybill', models.CharField(max_length=7)),
            ],
        ),
    ]
