# Generated by Django 3.2.5 on 2021-07-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0005_alter_post_estimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanup',
            name='amount',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cleanup',
            name='organizer_contact',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
