# Generated by Django 3.2.5 on 2021-07-28 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0006_auto_20210728_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='clean_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='environment.cleanup'),
            preserve_default=False,
        ),
    ]
